OK-404: Uusi rajapinta hakukohteiden hakemiseksi
Opetushallitus/konfo-backend pull request #200
Opened 2023-11-29 12:23 UTC by tomikat

2023-11-30 12:16 UTC, pretseli requested changes

2023-11-30 12:16 UTC, pretseli commented on src/konfo_backend/search/hakukohde/search.clj
> +    {:bool {:must terms, :filter {:term {:tila "julkaistu"}}}}))
Tarviiko `let`:iä johonkin tässä? Vois olla selkeämpi ilman. Pilkkua ei ainakaan tarvi :wink: 
```suggestion
  (let [terms {:term {:kohdejoukko.koodiUri kohdejoukko}}]
    {:bool {:must terms :filter {:term {:tila "julkaistu"}}}}))
```

2023-12-01 08:29 UTC, tomikat commented on src/konfo_backend/search/api.clj
> +   |  /search/hakukohteet:
Hyvää työtä! Vähän ihmettelinkin että tosiaanko näitä stringeinä muodostetaan. 😄  Lisäsin tälle uudelle rajapinnalle response-skeeman, siirsin api-määrityksen vastaavan muotoiseksi ja rebasetin tämän branchin OK-376:n päälle.

Tulevaisuuteen jäi vielä vanhojen rajapintojen api-kuvausten konvertointi.

2023-12-01 08:30 UTC, tomikat commented on src/konfo_backend/search/hakukohde/search.clj
> +    {:bool {:must terms, :filter {:term {:tila "julkaistu"}}}}))
Siivosin tämän!

2023-12-05 07:35 UTC, pretseli approved these changes

2023-12-14 20:42 UTC, merged